# Generated by Django 5.2.7 on 2025-10-23 13:08

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrender',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrender',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='projectrender',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='profile_image_height', help_text='Main profile picture', null=True, upload_to='profile/', width_field='profile_image_width'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=versatileimagefield.fields.VersatileImageField(height_field='featured_image_height', help_text='Main project image', upload_to='projects/featured/', width_field='featured_image_width'),
        ),
        migrations.AlterField(
            model_name='projectrender',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='image_height', help_text='Project screenshot or render', upload_to='projects/renders/', width_field='image_width'),
        ),
    ]
